name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'
      - 'version_*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create clean plugin zip
        run: |
          mkdir build
          cp -r "Layer Renamer" "build/Layer Renamer"
          cd build
          zip -r "../Layer Renamer.zip" "Layer Renamer"

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: "Layer Renamer.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
